on: [push, pull_request]

name: UnitTest
jobs:
  unittest-runner:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print current dir
        run: pwd
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Setup uv
        uses: hynek/setup-cached-uv@v2
      - name: Install Python dependencies
        run: |
          uv sync --all-extras
      - name: Run python unittest
        run: |
          source .venv/bin/activate
          python -m unittest tests/test_*.py

  ruff-checker:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Setup uv
        uses: hynek/setup-cached-uv@v2
      - name: Install Python dependencies
        run: |
          uv sync --all-extras
      - name: Check code style
        run: |
          source .venv/bin/activate
          ruff check --output-format=full --fix --show-fixes
      - name: Check format
        run: |
          source .venv/bin/activate
          ruff format . --check
